Cargo Borg
psychonaut-station/PsychonautStation pull request #228
Opened 2024-01-30 15:40 UTC by RengaN02

## Pull Request Hakkında
Oyuna cargo borg ekler.

Daha sprite yapılmadı o yüzden demo bi sprite yaptım. O yüzden lütfen **MERGELEMEYİN**
## Oyun için neden gerekli
Roleplayi arttırabilir.
## Sorunlar
![image](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/593b5733-4df6-4552-9d5b-d19af351c3bf)
![image](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/87595528-f30e-45eb-a4a1-355b1a3290e6)
Borg spritesi ve modül spritesini psychonaut klasörüne ekleyemedim, ekleyince spriteler gözükmüyor, ne yapsamda düzeltemedim...

![image](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/939bd551-bf44-42d0-9a97-85bf04e9f89c)
Soldaki spawn ile oluşturulan cargo borg,
sağdaki dönüşerek olduğumuz cargo borg.

## Changelog

:cl:
add: Cargo borg eklendi
/:cl:

2024-01-30 15:40 UTC, RengaN02 commented
LAN NEDEN OMEGA COMMİTİ VAR BURDA

2024-01-30 19:54 UTC, Seefaaa requested changes
iconları psychonaut'a taşımayı iyice daha dene

2024-01-30 19:54 UTC, Seefaaa commented on code/game/objects/items/mail.dm
> +		itemcontents -= item
ki z'ye basınca yapıyodu zaten

2024-01-30 19:54 UTC, Seefaaa commented on code/game/objects/items/mail.dm
> +		item.forceMove(target_turf)
```suggestion
/obj/item/storage/bag/mail/borg/afterattack(atom/target, mob/user)
	. = ..()
	if(.)
		return
	if(length(contents))
		var/turf/target_turf = get_turf(target)
		if(!isturf(target_turf))
			return
		var/pick = tgui_input_list(user, "Which one will you drop?", "Mail Bag", contents)
		if(isnull(pick))
			return
		atom_storage.attempt_remove(pick, target_turf)
```
storage'nin kendi proclarıyla yaparsan daha iyi olur

2024-01-30 19:54 UTC, Seefaaa commented on code/game/objects/items/robot/items/storage.dm
> +		stored_copy.plane = FLOAT_PLANE
bunlar başka şeylerin de üzerinde gözükmesine sebep olmuyodur umarım

2024-01-30 19:54 UTC, Seefaaa commented on code/game/objects/items/robot/items/storage.dm
> +		return ..()
```suggestion
/obj/item/borg/apparatus/paper_holder/pre_attack(atom/target, mob/living/user, params)
	if(istype(target, /obj/item/paper_bin) && !stored)
		var/obj/item/paper_bin/paperbin = target
		if(paperbin.total_paper > 0)
			var/obj/item/paper/top_paper = pop(paperbin.paper_stack) || paperbin.generate_paper()
			paperbin.total_paper -= 1
			top_paper.forceMove(src)
			stored = top_paper
			RegisterSignal(stored, COMSIG_ATOM_UPDATED_ICON, PROC_REF(on_stored_updated_icon))
			to_chat(user, span_notice("You take [top_paper] out of [paperbin]."))
			paperbin.update_appearance()
			update_appearance()
		return TRUE
	return ..()
```
yapabiliyor mu bilmiyorum ama folder ve clipboardın içine de koyabilse iyi olurdu ve masaya

2024-01-30 19:54 UTC, Seefaaa commented on code/game/objects/items/robot/items/storage.dm
> +	. += span_notice(" <i>Alt-click</i> will drop the currently stored paper. ")
```suggestion
	. += span_notice(" <i>Alt-click</i> to drop the currently stored paper. ")
```

2024-01-30 19:54 UTC, Seefaaa commented on code/game/objects/items/robot/items/tools.dm
> +	for(var/atom/movable/crate as anything in stored_crates)
```suggestion
	for(var/obj/crate as anything in stored_crates)
```
taa atom/moveable'dan yapmana gerek yok başka yerlerde de yapmıssın bunu anlaşılabilirlik daha önemli

2024-01-30 19:54 UTC, Seefaaa commented on code/game/objects/items/robot/items/tools.dm
> +		if(target_turf.is_blocked_turf())
```suggestion
		if(isturf(target_turf) && target_turf.is_blocked_turf())
```

2024-01-30 19:54 UTC, Seefaaa commented on code/game/objects/items/robot/items/tools.dm
> +	. += span_notice(" <i>Alt-click</i> will drop all the crates. ")
```suggestion
	. += span_notice(" <i>Alt-click</i> to drop all the crates. ")
```

2024-01-30 19:54 UTC, Seefaaa commented on code/modules/mob/living/silicon/robot/robot_model.dm
> +		/obj/item/borg/stun,
daha unique bir şey iyi olurdu

2024-01-30 19:54 UTC, Seefaaa commented on code/modules/mob/living/silicon/robot/robot_model.dm
> +		/obj/item/stack/wrapping_paper,
bitince yok olmuyor mu bunlar

2024-01-30 19:54 UTC, Seefaaa commented on code/game/objects/items/robot/items/tools.dm
> +/obj/item/borg/cyborg_clamp/proc/check_crate_pickup(atom/movable/target)
adı can_pickup falan olsa daha iyi olur mantıksız geldi bana şuanki adı

2024-01-30 19:58 UTC, RengaN02 commented on code/game/objects/items/robot/items/storage.dm
> +		stored_copy.plane = FLOAT_PLANE
kağıt tutucuyu tutan şeyin spritesinin üste gelmesini saglıyo, onuda sadece borgu oynayan kişi görüyo yani sıkıntı değil ayrıca diğer appartuslardada var aynısı

2024-01-30 19:58 UTC, RengaN02 commented on code/game/objects/items/robot/items/storage.dm
> +		return ..()
onlarada bakarım

2024-01-30 21:08 UTC, RengaN02 commented
icon olayını yarın denicem

2024-01-31 12:39 UTC, RengaN02 commented
> iconları psychonaut'a taşımayı iyice daha dene

hallettim

2024-01-31 13:39 UTC, Seefaaa commented
daha unique dediğim batondan farklı bir şey olmasıydı paper_holder eşyasının adı değil eski adı daha iyi paper_holder'in

package wrapper 0'a ulaştığında yok olup carboard tube oluyor sana demek istediğim recharge datumu ekle değildi ki zaten stack olduğu için latheden falan alabilirsin stackleyip. charge datumuna gerek yok. cardboard tube olduğunda da geri stackleyemeyeceğinden dolduramazsın

2024-01-31 14:16 UTC, RengaN02 commented
batondan başka ne ekleyebilcegimi bilmiyorum

2024-01-31 14:16 UTC, RengaN02 commented
düşünmem lazım

2024-01-31 14:47 UTC, Seefaaa commented
> > daha unique dediğim batondan farklı bir şey olmasıydı paper_holder eşyasının adı değil eski adı daha iyi paper_holder'in aklına bir şey gelmiyosa baton kalsın
> > package wrapper 0'a ulaştığında yok olup carboard tube oluyor sana demek istediğim recharge datumu ekle değildi ki zaten stack olduğu için latheden falan alabilirsin stackleyip. charge datumuna gerek yok. cardboard tube olduğunda da geri stackleyemeyeceğinden dolduramazsın
> 
> package wrapperin 0a ulaşma ihtimali yok çünkü borglar o eşyayı kullanınca amountu düşmüyor onun yerine robot_energy_storage datumununun energysini kullanıyor

öyleyse wrapperlara /borg diye subtype ekleyip is_cyborg = TRUE ve cost = x yapsan daha iyi olur heralde

2024-01-31 14:54 UTC, Seefaaa commented
clampın sınırsız range var

2024-01-31 15:05 UTC, Seefaaa commented
mailbag z bastığında zaten tüm eşyaları bırakıyor altclick gereksiz. ikisinden birini olduğu yere tıklayınca olduğu gibi bırakma yapsan daha iyi olur eğer kalsın istiyorsan
mailbagin de range sınırsız
mailbagi boşalttığında ui açık ise maili yine de fırlatabiliyorusn

2024-01-31 16:22 UTC, RengaN02 commented
kargo borga upgrade olarak kinesis module eklemeyi düşünüyorum

2024-01-31 16:50 UTC, Seefaaa commented
olmaz kinesis borg için fazla

2024-01-31 17:27 UTC, Seefaaa requested changes
mailbagi hala uzaktan kullanabiliyorsun
- yere tıkla
- ui açılsın
- tıkladığın yerden uzaklaş
- uidan seçip submitle
- mail önceden tıklamış olduğun yere ışınlansın

2024-01-31 17:27 UTC, Seefaaa commented on code/game/objects/items/robot/items/tools.dm
> +			balloon_alert(user, "interrupted!")
```suggestion
```

2024-01-31 17:27 UTC, Seefaaa commented on code/game/objects/items/robot/items/tools.dm
> +			balloon_alert(user, "interrupted!")
```suggestion
```
do_after yeterince feedback veriyor

2024-01-31 20:06 UTC, Seefaaa commented on icons/mob/silicon/robots.dmi
biliyorum aynı olduğunu ama modified gözüküyor

2024-01-31 21:31 UTC, RengaN02 commented on icons/mob/silicon/robots.dmi
bunu düzeltmeyi bi denerim

2024-02-01 10:53 UTC, Seefaaa commented
anchorlu crateleri ve eşyaları da kaldıramaması lazım

2024-02-01 11:39 UTC, RengaN02 commented
Box cutteri paketlenmiş bi kutuda kullanınca kutu oldugumuz yere geliyodu, onu düzelttim

2024-02-01 11:54 UTC, RengaN02 commented
test merge acılırmı yeni sprite gelene kadar

2024-02-01 12:56 UTC, Seefaaa commented
yok sprite gelince bakarız

2024-02-11 12:02 UTC, RengaN02 commented
![image](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/b6e3a354-ea3e-405a-a278-dfb1cf57829c)
skyrattan bu resmi ekledim robot süpürge olarak

2024-02-11 12:03 UTC, RengaN02 commented
cargo borg icin halletmeye calıscam spriteyi

2024-02-11 12:04 UTC, RengaN02 commented
tekrar bakınca kötü geldi
kaldırıyom

2024-03-01 19:55 UTC, RengaN02 commented
create and destroydan sonra tile yok olup sonra diger test bok oluyo, delirticek

2024-03-01 22:04 UTC, RengaN02 commented
![image-15-01.jpeg](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/9d6a74e5-6bc8-47aa-b330-bad223acb631)

2024-03-04 13:15 UTC, RengaN02 commented
Borg icin hand labeler varmis zaten amk

2024-03-16 17:41 UTC, Seefaaa commented on code/game/objects/items/robot/items/generic.dm
> +		shoot(target, user, click_params)
fırlatmasa da enerji harcayacak

2024-03-16 17:41 UTC, Seefaaa commented on code/game/objects/items/robot/items/generic.dm
> +	icon_state = "crossbow"
en azından crossbow_halloween olsun kendin eklemeyeceksen

2024-03-16 17:41 UTC, Seefaaa commented on code/game/objects/items/robot/items/generic.dm
> +	var/obj/item/paperplane/syndicate/hardlight/plane_to_fire = new /obj/item/paperplane/syndicate/hardlight(get_turf(src.loc))
get_turf(loc)

2024-03-16 19:28 UTC, RengaN02 commented
Preview diye attığım comitin adını yanlış seçtim, normalde sync olcakti

2024-03-19 14:39 UTC, Seefaaa commented
cooldownı 5 saniye ve kullandığı enerjiyi biraz arttırıp sarjını sınırsız yapabilirsin böylece gercekten kağıt temalı mini crossbow olur ve stunlocka alamaz

2024-03-22 14:54 UTC, RengaN02 commented
Commiti atamadim sanip sync commitinin adini yanlis sectim, cokguzel

2024-03-23 22:36 UTC, Seefaaa commented on code/game/objects/items/robot/items/tools.dm
> +	if(length(carrying_humans) > 0)
```suggestion
	if(length(carrying_humans))
```

2024-03-23 22:37 UTC, Seefaaa commented on code/game/objects/items/robot/items/tools.dm
> +	carrying_humans = list()
```suggestion
	carrying_humans.len = 0
```

2024-03-23 22:38 UTC, Seefaaa commented
lazylist kullanabilirsin kargo borgun emaglenmesi epey nadir bir durum olacağından

2024-03-24 10:42 UTC, RengaN02 commented
> lazylist kullanabilirsin kargo borgun emaglenmesi epey nadir bir durum olacağından

yaptım

2024-03-25 15:10 UTC, Seefaaa commented on code/game/objects/items/robot/items/tools.dm
> +	var/list/carrying_humans = list()
lazy listin başta null olması gerek

2024-03-25 15:12 UTC, Seefaaa commented on code/game/objects/items/robot/items/tools.dm
> +	var/list/carrying_humans = list()
```suggestion
	var/list/carrying_humans
```
lazy listin başta tanımlı olmaması gerek olayı o zaten

2024-04-06 12:49 UTC, Seefaaa commented
daha ekleme yapmayacaksan mergeleyelim

2024-04-06 12:50 UTC, RengaN02 commented
> daha ekleme yapmayacaksan mergeleyelim

tabi, başka bişey kalmadi sanirsam

2024-04-06 12:54 UTC, Seefaaa commented
animasyon çizmiştin onu ekleyecek misin

2024-04-06 14:10 UTC, Seefaaa approved these changes

2024-04-06 14:43 UTC, merged