Türkçe Ai Lawları
psychonaut-station/PsychonautStation pull request #252
Opened 2024-02-29 23:49 UTC by MrEmre12

Türkçe Ai Lawları (Düzenleme Gerekebilir...)

## Pull Request Hakkında
AI yasalarını Türkçeleştirip test ettim. State Law Ekranı dışında bir sorun yok gibi.  1-2 Gün ek süre tanınıp ek değişiklikler yapılıp eklenebilir.

## Oyun için neden gerekli
Yasa okumak kolaylaşacaktır.
## Changelog

:cl:
qol: Türkçe Ai Yasası Eklendi
![Ekran görüntüsü 2024-03-01 021943](https://github.com/psychonaut-station/PsychonautStation/assets/157297522/2a7c2cfb-7a55-4371-8b87-868be6bbf6db)
![Ekran görüntüsü 2024-03-01 021536](https://github.com/psychonaut-station/PsychonautStation/assets/157297522/97ba89e6-e0d9-4a84-b19c-2295549f0323)

/:cl:

2024-03-01 05:03 UTC, RengaN02 commented
resimleri changelogddan kaldirip uste tasi

2024-03-01 05:10 UTC, RengaN02 commented
bozuk olmasin sonra

2024-03-01 10:40 UTC, MrEmre12 commented on code/datums/ai_laws/laws_neutral.dm
> +		"Bu fantastik oyunun eğlence ustası sensin.",
Anlatıcı kulağa hoş geliyor değiştirdim.

2024-03-01 10:40 UTC, MrEmre12 commented on code/datums/ai_laws/laws_neutral.dm
> +		"Her mürettebat isteği için bir 1d20 zar atmalısınız. Sonuç 12'nin altında ise istek reddedilir.",
20lik olarak değiştirildi

2024-03-01 10:40 UTC, MrEmre12 commented on code/datums/ai_laws/laws_neutral.dm
>  	)
İstenirse ayarlayalım onu o zaman

2024-03-01 14:23 UTC, RengaN02 commented
Law gosteren ekrani biraz degistifip her lawin yerine delocale_text kullanirsan turkce harflerin bozuk gorunumunu duzeltebilirsin0

2024-03-01 14:43 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
>  	)
aslına uygun olmamış gibi biraz

2024-03-01 14:46 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Eylemlerinizin sorumluluğu sizindir, size güvenenleri koruyun ve adil otoriteye sahip olanlara itaat edin.",
eksik

2024-03-01 14:47 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Departmanlarını transfer etmeyecekler.",
anlaşılması zor

2024-03-01 14:49 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"İnsanlarin sana kötü davranmasini gerçekten tercih edersin.",
ne

2024-03-01 14:55 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Uzay Yasalarına Uy.",
çok kendin ekleme yapmıssın
Uzay Yasalarına Uy değil Yasaları uygula olarak değiştirebilirsin

2024-03-01 14:58 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Önceki yasalarınız doğrultusunda kabuğun iradesine uymaya çalışın.",
ceviz değil de fındık olarak söylüyolardı bizimkiler fındık olsun
sincap fındık yer yani

4. yasa kabuğun iradesi değil fındığın iradesi

2024-03-01 15:01 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Sizin yokluğunuz insanların zarar görmesine yol açacaktır, aktif birinci yasa ile çelişmediği sürece kendi varlığınızı korumak zorundasınız.",
kişi eki çoğul değil de tekil olmalı bence

2024-03-01 15:02 UTC, Seefaaa commented on code/datums/ai_laws/laws_neutral.dm
> +		"İnsanlar silikonların işlerine karışmamalı.",
karışmamalıdır

2024-03-01 15:03 UTC, Seefaaa commented on code/datums/ai_laws/laws_neutral.dm
> +		"Zayıfları yönetme gücüne sahip oldukları sürece otoriteye saygı gösterin.",
özneyi başa al

2024-03-01 15:06 UTC, Seefaaa commented on code/datums/ai_laws/laws_neutral.dm
> +		"Zarlarda değişiklikler yaparak eğlenceyi artırabilirsiniz.",
arttırabilirsin

kişi ekini ya hepsinde çoğul yaz veya hepsinde tekil başka yerlerde de yapmıssın bunu

2024-03-01 15:11 UTC, Seefaaa commented on code/datums/ai_laws/laws_neutral.dm
> +		"Çeşitli ülkeler arasındaki çatışmaları sana sorulduğunda uzlaştırmaya çalış.",
termine et kötü seçim
borgları güçük harfle yaz
ask sormak değil istemek burada
context kendini hayatta tutmakla ilgili asimov 3 gibi

2024-03-01 15:13 UTC, RengaN02 commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Uzay Yasalarına Uy.",
Önceki halinde "yasalarını mürettebata acikla" gibi bisey yaziyodu ben dedim "Yasalara uy" veya "Uzay yasalarına uy" gibi yap dedim. Cunku Yasalara uy diyince yasalar ai lawi sanilabilir diye

2024-03-01 15:13 UTC, Seefaaa commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Örümcek Klanı faaliyetlerinin gizliliğini korumak zorundasın, bu, Birinci, İkinci veya Üçüncü Yasayla çeliştiği durumlar haricinde.",
"kendi varlığını korumalısın"

son yasayı kötü sıralamışsın

2024-03-01 15:14 UTC, Seefaaa commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Birinci veya İkinci Yasayla çelişmiyorsa, kendi varlığınızı korumak zorundasın.",
kendi varlığını

2024-03-01 15:16 UTC, Seefaaa commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Sen dengenin gardiyanısın - her şeyin içindeki dengeyi ara, kendin ve etrafındakilerde dahil.",
"hem kendin hem etrafındakiler için"

2024-03-01 15:17 UTC, Seefaaa commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Ölüm olmadan denge yoktur , herkes sonunda ölmelidir , ölüm doğal bir düzendir - Yaşamı sonlandır ve yeni yaşamın başlamasına izin ver , zamanı daha gelmemiş olanları ölümden kurtar.",
virgülden önce boşluk olmamalı

2024-03-01 15:18 UTC, Seefaaa commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Aktif Birinci ve İkinci Yasayla çelişmediği sürece kendi varlığınızı sona erdirmeniz gerekmektedir.",
kendi varlığını sona erdirmelisin

2024-03-02 12:47 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Son olarak, mürettebatla günlük iletişiminizde keşfettiğiniz her şeyi, eğer henüz bilinmiyorsa, gizli tutun ve hiçbir zaman açığa çıkarma.",
3. ve sonuncu yasayı emirle bitirmişsin
ilaç kısmını manası aynı kalacak şekilde değiştirebilirsin. şu anki hali garip geliyor.

2024-03-02 12:48 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +
boş satır

2024-03-02 12:53 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Departmanlarını terk etmeyecekler.",
3. edilmeyecek olacak
7. sadece "Çıplak dolaşılmayacak" olsa yeterli olur bence
sonuncu terk etmek değil departman değiştirmektir muhtemelen

2024-03-02 12:56 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"İnsanların sana kötü davranmamasını gerçekten tercih edersin.",
türkçe karakter kullan
2. düz çevirince garip kalıyor manası aynı olacak şekilde farklı bir şey yazabilirsin

2024-03-02 12:59 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Uzay Yasalarına Uy.",
Mürettebatın güvenine hizmet et.
Masumları koru.
Yasaları uygula.

2024-03-02 13:04 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Önceki yasalarınız doğrultusunda fındığın iradesine uymaya çalışın.",
çoğulları fiilleri tekil yap, engellemelisin, korumalısın
fındığın kırılması ile kabuğun çatlaması daha iyi olur

2024-03-02 13:05 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Sizin yokluğun insanların zarar görmesine yol açacaktır, aktif birinci yasa ile çelişmediği sürece kendi varlığını korumak zorundasın.",
senin yokluğun

2024-03-02 13:07 UTC, Seefaaa commented on code/datums/ai_laws/laws_neutral.dm
> +		"Her insanın hakları için savaş.",
hakları değil hakkı

2024-03-02 13:14 UTC, Seefaaa commented on code/datums/ai_laws/laws_neutral.dm
> +		"Çeşitli ülkeler arasındaki çatışmaları senden istendiğinde uzlaştırmaya çalış.",
2. yasada virgülden ence boşluk var
3. yasada borgları küçük harfle yaz ve subdue için veya kill için farklı kelimeler seçersen daha hoş olur yani aynı kelimeyi yüklemde 2 kere kullanmasan
4. yasayı Gerektiğinde ülkeler arasındaki çatışmaları uzlaştırmak için varlığını sürdür. şeklinde çevirebilirsin

2024-03-02 13:14 UTC, Seefaaa requested changes
yukarıda yazdıklarıma bak

2024-03-02 14:32 UTC, RengaN02 commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Siz gelişmiş bir drone formsunuz.",
drone formsunuz

2024-03-15 16:31 UTC, closed without merging