New Station Ankara Station
psychonaut-station/PsychonautStation pull request #271
Opened 2024-03-29 12:19 UTC by MrEmre12

## Pull Request Hakkında

Biten departmanlar: Servis, Kargo ve Arrivals, %80 oranında tamamlanmıştır.

Eklenmesi planlanan şeyler: Motel, kargo shuttle, evac, arrivals shuttle ve medbay

Gezegen yüzeyine kurulmuş olan eski ancak etkileyici bir koloni istasyonu, departmanları birbirinden ayıran geniş bir otobana ve departmanlar arasındaki binaların minik sokaklarına sahiptir.

İlk kat sadece maden işlerini kapsar. İkinci katta ise su kanalları, otoban, yaşam alanları ve keşfedilebilir alanların çoğu bulunmaktadır. Üçüncü kat ise insanların kalan işlerini gerçekleştirdiği ek odaları ve bakım ekiplerinin bulunduğu eski, yıkık dökük bir kat olarak bilinir.

![StrongDMM-2024-03-29 15 06 12](https://github.com/psychonaut-station/PsychonautStation/assets/157297522/7067b5d4-9cbd-4cb5-81e8-560e19646156)

## Oyun için neden gerekli

Metanın mektup sistemini, Northstar'ın geniş sokaklarını ve diğer birçok harita özelliğini tek bir noktada harmanlar. Kütüphanenin bahçesi, botaniğin genişliği ve mutfak ile barın geniş olması gibi farklı yanları ile öne çıkar. Kargonun ayrı ayrı sokak gibi olması da Haritanın, "nations" ve "zombi eventleri" için uygun olduğunu gösterir.

## Changelog

:cl:
add: Yeni Map Ekler
/:cl:

2024-03-29 12:47 UTC, exdal commented
yeni map ekler diye bir changelog yok, mapin ismini duzgun yaz

2024-04-27 19:26 UTC, MrEmre12 commented
AnkaraStation haritasını tamamlamak için yeterli zamanım yok ve oyuncuların ilgisini çekeceğinden emin değilim, bu yüzden başka bir karar alınıncaya kadar PRİ'yi kapatmaya karar verdim.

2024-08-03 18:58 UTC, RengaN02 commented on _maps/ankarastation.json
> +	"map_file": "Ankarastation.dmm",
```suggestion
	"map_file": "AnkaraStation.dmm",
```

2024-08-03 18:59 UTC, RengaN02 commented on _maps/ankarastation.json
> +	"map_file": "Ankarastation.dmm",
hata bu

2024-09-27 14:02 UTC, Seefaaa requested changes

2024-09-27 14:02 UTC, Seefaaa commented on code/modules/vehicles/cars/taxi.dm
taxi'nin kodu neredeyse retroline'ın aynısı copypaste yapmıssın sadece. eğer böyle olacaksa copypaste yapmak yerine taxiyi retroline'ın subtype'ı yap iconu falan değiştir sadece anlayacağın

2024-10-08 17:32 UTC, closed without merging