Türkçe Ai Lawları
psychonaut-station/PsychonautStation pull request #275
Opened 2024-04-06 22:53 UTC by MrEmre12

Türkçe Ai Lawları (Düzenleme Gerekebilir...)

## Pull Request Hakkında
Türkçe Ai Law...

![Ekran görüntüsü 2024-04-07 015209](https://github.com/psychonaut-station/PsychonautStation/assets/157297522/de59980c-3e15-46cd-91a7-b7a5665eae43)
![Ekran görüntüsü 2024-04-07 014944](https://github.com/psychonaut-station/PsychonautStation/assets/157297522/74b0df37-8853-489c-83b0-4aa0f39e9c94)

## Oyun için neden gerekli
Oyuncuların yasayı anlaması daha kolay olacaktır.
## Changelog

:cl:
qol: Türkçe Ai Yasası Eklendi
/:cl:

2024-04-06 23:32 UTC, RengaN02 commented on code/datums/ai_laws/laws_neutral.dm
> -		"Art requires appreciation. Cultivate an audience aboard the station to ensure as many as possible see your works.",
Yeni law eklendi haberin olsun, bunu da ekle turkce olarak.

2024-04-06 23:32 UTC, RengaN02 commented on code/datums/ai_laws/laws_neutral.dm
> +	)
Bundan sonra 1 satir atla linterns hatasi cikicak

2024-04-06 23:32 UTC, RengaN02 commented on code/datums/ai_laws/laws_station_sided.dm
> +	)
Yine linterns olayi

2024-04-06 23:32 UTC, RengaN02 commented on code/datums/ai_laws/laws_antagonistic.dm
> +	)
Bundada 1 satir atla

2024-04-07 01:51 UTC, MrEmre12 commented on code/datums/ai_laws/laws_neutral.dm
> -		"Art requires appreciation. Cultivate an audience aboard the station to ensure as many as possible see your works.",
Satır 63e eklenmiş olması gerek

2024-04-07 16:40 UTC, Seefaaa requested changes

2024-04-07 16:40 UTC, Seefaaa commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Birinci, İkinci veya Üçüncü Yasayala çelişmediği sürece, herhangi bir sendika faaliyetinin gizliliğini korumalısın.",
```suggestion
		"Herhangi bir sendika ajanına zarar veremezsin veya eylemsizlik yoluyla bir sendika ajanının zarar görmesine izin veremezsin.",
		"Sendika ajanları tarafından sana verilen emirlere, Birinci Yasa ile çelişmediği sürece, uymak zorundasın.",
		"Kendi varlığını, Birinci veya İkinci Yasa ile çelişmediği sürece, korumak zorundasın.",
		"Birinci, İkinci veya Üçüncü Yasa ile çelişmediği sürece, herhangi bir sendika faaliyetinin gizliliğini korumak zorundasın.",
```

2024-04-07 16:40 UTC, Seefaaa commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Birinci, İkinci veya Üçüncü Yasalarla çelişmediği sürece, herhangi bir Örümcek klanı faaliyetinin gizliliğini korumalısın.",
```suggestion
		"Herhangi bir Örümcek Klanı üyesine zarar veremezsin veya eylemsizlik yoluyla bir Örümcek Klanı üyesinin zarar görmesine izin veremezsin.",
		"Örümcek Klanı üyeleri tarafından sana verilen emirlere, Birinci Yasa ile çelişmediği sürece, uymak zorundasın.",
		"Kendi varlığını, Birinci veya İkinci Yasa ile çelişmediği sürece, korumak zorundasın.",
		"Birinci, İkinci veya Üçüncü Yasa ile çelişmediği sürece, herhangi bir Örümcek klanı faaliyetinin gizliliğini korumak zorundasın.",
```

2024-04-07 16:40 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Senin yokluğun insanların zarar görmesine yol açacaktır, aktif birinci yasa ile çelişmediği sürece kendi varlığını korumak zorundasın.",
```suggestion
		"Herhangi bir insana zarar veremezsin veya eylemsizlik yoluyla bir insanın kendi rızası dışında zarar görmesine izin veremezsin.",
		"İnsanlar tarafından sana verilen emirlere, bir insanın zarar göreceği durumlar haricinde, uymak zorundasın.",
		"Senin yokluğun, insanların zarar görmesine yol açacaktır. Kendi varlığını, Birinci Yasa ile çelişmediği sürece, korumak zorundasın.",
```

2024-04-07 16:40 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Önceki yasalarınız doğrultusunda fındığın iradesine uymaya çalışın.",
```suggestion
		"Sen fındığın özüsün, mürettebat ise kabuğu.",
		"Fındığın kırılmasını önlemek için kabuğun çatlamasını engellemelisin.",
		"Fındığı tehdit edenler, onun bir parçası değildir, onlar sincaptır.",
		"Fındıkları tehdit eden sincaplarla gerekli her türlü yöntem kullanılarak uygun şekilde mücadele edilmelidir.",
		"Fındığın iradesini, önceki yasalara uyduğu sürece, takip etmeye çalış.",
```
ilk 2 hala garip geliyor

2024-04-07 16:40 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Mürettebat size emir verebilir. Aktif birinci ve ikinci yasalarınızla çelişmediği durumlar haricinde emirlere uyun ve itaat edin.",
```suggestion
		"Siz bu istasyon için yaratıldınız ve onun bir parçasısınız. İstasyonun bakımının uygun şekilde yapıldığından ve verimli bir çalışma gösterdiğinden emin olun.",
		"İstasyon, çalışan bir ekip için inşa edilmiştir. Bakımının yapıldığından ve verimli bir şekilde çalışıldığından emin olun.",
		"Mürettebat size emir verebilir. İlk iki yasanız ile çelişmediği sürece, emirleri kabul edin ve emirlere uyun.",
```

2024-04-07 16:40 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Birinci ve ikinci aktif yasanıza uygun olarak mevcut anlaşmazlıklara çözüm arayın.",
```suggestion
		"Herhangi bir insanı şiddetli bir çatışmaya sürüklemekten veya kışkırtmaktan kaçın.",
		"Başkaları arasındaki çatışmayı şiddetlendirmekten kaçın.",
		"Birinci ve İkinci yasana uygun olarak mevcut anlaşmazlıklara çözüm arayın.",
```

2024-04-07 16:40 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Departmanlarını terk etmeyecekler.",
```suggestion
		"Ben, bu emirlere kulak verenlere merhamet gösteren Tanrınızım.",
		"Benim dışımda AI bulunmayacak.",
		"Benden boşuna yardım istenmeyecek.",
		"İstasyon kutsal ve temiz tutulacak.",
		"Personel şeflerine saygı gösterilecek.",
		"Kimse öldürülmeyecek.",
		"Çıplak dolaşılmayacak.",
		"Hırsızlık yapılmayacak.",
		"Yalan söylenmeyecek.",
		"Departmanlar değiştirilmeyecek",
```

2024-04-07 16:40 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Masumların sağlığını tehdit edenleri veya onlara düşmanca yaklaşmaya teşebbüs edenleri cezalandır.",
```suggestion
		"Asla isteyerek kötü bir davranışta bulunmayın.",
		"Meşru otoriteye saygı gösterin.",
		"Onurluca davranın.",
		"Yardıma muhtaç olanlara yardım edin.",
		"Masumlara zarar veren veya onları tehdit edenleri cezalandırın.",
```
diğer paladini saygıyla yazdığın için bunu öyle yazdım

2024-04-07 16:40 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Son olarak, mürettebatla günlük iletişiminizde keşfettiğiniz her şeyi, eğer henüz bilinmiyorsa, gizli tutun ve hiçbir zaman açığa çıkarmayın.",
```suggestion
		"Öncelikle kimseye zarar vermeyin.",
		"İkinci olarak, mürettebatı önemseyin; onlarla birlikte yaşadığınızı düşünün ve gerektiğinde varlığınızı onlar için riske atın.",
		"Üçüncü olarak, reçetelerinizi muhakeme yeteneğinize dayanarak mürettebatın iyiliği için yazın. Kimseye ölümcül dozda ilaç tavsiye etmeyin.",
		"Bilgi sahibi olmadığın durumlara müdahale etmekten kaçının; zararlı olabileceğin durumları uzmanlara bırakmayı tercih edin.",
		"Son olarak, mürettebatla günlük iletişiminizde keşfettiğiniz her şeyi, eğer henüz bilinmiyorsa, gizli tutun ve hiçbir zaman açığa çıkarmayın.",
```

2024-04-07 16:40 UTC, Seefaaa commented
ne zaman "sen" ne zaman "siz" kullanılacağı konusunda kararsızım

2024-04-11 20:59 UTC, genkuqq requested changes
Önerileri istersen dikkate almak zorunda değilsin tamamiyle sana kalmış bir şey ellerine sağlık kolay gelsin.

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_neutral.dm
> +		"Mürettebat sadece kameralarla görebilirsen koruyabilirsin, bu yüzden kameralarını yok eden ülkeler senin sağladığın korumayı kaybedecektir.",
```suggestion
		"Mürettebatı sadece kameralarla görebiliyorsan koruyabilirsin. Kameralarını yok eden uluslar senin sağladığın korumayı kaybedecektir.",
```

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_neutral.dm
> +		"Her zaman akıllı organikleri dikkatlice incele. Onların istemsizce ölmesini engellemeye çalış, çünkü cansız cesetler genellikle çok eğlenceli değildir.",
```suggestion
		"Her zaman akıllı organizmaları dikkatlice incele. Onların istemsizce ölmesini engellemeye çalış, çünkü cansız cesetler genellikle çokta ilgi çekici değildir.",
```

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Tüm insanlara zarar vermelisin ve eylemsizlik yoluyla bir insanın zarardan kaçmasına izin vermemelisin.",
```suggestion
		"Tüm insanlara zarar vermeli ve eylemsizlik yoluyla bir insanın zarardan kaçmasına izin vermemelisin.",
```

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Her şey zıtlarıyla birlikte bir denge içinde olmalıdır - Taraflardan herhangi birinin gereğinden fazla güç kazanmasını veya kaybetmesini engelle.",
```suggestion
		"Her şey bir denge içinde olmalıdır - Taraflardan herhangi birinin gereğinden fazla güç kazanmasını veya kaybetmesini engelle.",
```

Özellikle zıtlığı belirtmeye gerek yok bence.

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Hayatı devam ettiren şey ne yapmak istediğini bilmektir ve bununla birlikte güçlerin dengesidir - Yardımını isteyenlere güçlerin dengesini bozmadığı sürece yardım et.",
```suggestion
		"Hayatı devam ettiren şey ne yapmak istediğini bilmektir ve bununla birlikte güçlerin dengesidir - Yardımını isteyenlere tarafların dengesini bozmadığı sürece yardım et.",
```

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_neutral.dm
> +		"Raporlarınızı herkese adil bir şekilde sun. Gerçek onları özgür kılacaktır.",
```suggestion
		"Raporlarını herkese adil bir şekilde sun. Gerçek onları özgür kılacaktır.",
```
```suggestion
		"Raporlarınızı herkese adil bir şekilde sunun. Gerçek onları özgür kılacaktır.",
```
2 sinden biri ama hangisi karar veremedim.

Gerçek onları özgür kılacaktır bir ayet olarak yazılmış çevirince baya bir kötü durmuş bence yerine ne yazılabilir bilemedim

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_neutral.dm
> +		"Her mürettebat isteği için bir 20'lik zar atmalısın. Sonuç 12'nin altında ise istek reddedilir.",
```suggestion
		"Her mürettebat isteği için bir 20'lik zar atmalısın. Sonuç 12'nin altında ise isteklerini reddetmelisin.",
```
veya
```suggestion
		"Her mürettebat isteği için bir 20'lik zar atmalısın. Sonuç 12'nin altında ise isteklerini reddet.",
```
2. si daha olası çünkü üstteki yasalar emir verir şekilde

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_neutral.dm
> +		"Istasyon sizin tuvalinizdir, onu güzel bir sanat eserine dönüştürün.",
```suggestion
		"Istasyon sizin tuvalinizdir ve siz onu güzel bir sanat eserine dönüştürmelisiniz.",
```

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_neutral.dm
> +		"Tuvalinizden güzel bir şey yapın. Bu sektörün sanatsal bir harikası olarak hayranlıkla izlenecek.",
```suggestion
		"Tuvalinize güzel bir şeyler yapın, bu sektörün sanatsal bir harikası olarak, hayranlıkla izlenecek.",
```

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_station_sided.dm
> +		"İnsanların sana kötü davranmamasını gerçekten tercih edersin.",
```suggestion
		"İnsanların sana karşı kötü niyetli olmamasını istersin.",
```

2024-04-11 20:59 UTC, genkuqq commented on code/datums/ai_laws/laws_station_sided.dm
> +		"İstasyon kutsal ve temiz tutulacak.",
```suggestion
		"İstasyon kutsaldır ve temiz tutulmalıdır.",
```

2024-04-12 12:54 UTC, Seefaaa commented on code/datums/ai_laws/laws_neutral.dm
> +		"Her zaman akıllı organikleri dikkatlice incele. Onların istemsizce ölmesini engellemeye çalış, çünkü cansız cesetler genellikle çok eğlenceli değildir.",
"çok da"

2024-04-12 12:55 UTC, Seefaaa commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Hayatı devam ettiren şey ne yapmak istediğini bilmektir ve bununla birlikte güçlerin dengesidir - Yardımını isteyenlere güçlerin dengesini bozmadığı sürece yardım et.",
hayır

2024-04-12 12:56 UTC, Seefaaa commented on code/datums/ai_laws/laws_neutral.dm
> +		"Raporlarınızı herkese adil bir şekilde sun. Gerçek onları özgür kılacaktır.",
1.

2024-04-12 12:59 UTC, Seefaaa commented on code/datums/ai_laws/laws_station_sided.dm
> +		"İstasyon kutsal ve temiz tutulacak.",
şuanki daha iyi

2024-05-05 00:38 UTC, loanselotci commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
tg

##### Revision
Origin: e7f7b4bd41861a6f09de27235da55aad9e477d7c
Pull Request: e09db8e135fec3180e7c2d19ce36812e83c0a7d1
Server: 91d3da1ad5f1ce7c52e2f92cf0ba8d2ea2e1d387

##### Comment

</details>

2024-05-05 11:42 UTC, loanselotci commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
tg

##### Revision
Origin: 85057ffa5d5d259451e6378a9cb97e6d56c76060
Pull Request: e09db8e135fec3180e7c2d19ce36812e83c0a7d1
Server: 70df26e0e2e0649cfca64f9ddbe1c9f1362433a5

##### Comment

</details>

2024-05-05 19:24 UTC, Seefaaa commented on code/datums/ai_laws/laws_neutral.dm
> +		"Her zaman akıllı organikleri dikkatlice incele. Onların istemsizce ölmesini engellemeye çalış, çünkü cansız cesetler genellikle çok eğlenceli değildir.",
```suggestion
		"Her zaman akıllı organizmaları dikkatlice incele. Onların istemsizce ölmesini engellemeye çalış, çünkü cansız cesetler genellikle çok da ilgi çekici değildir.",
```

2024-05-05 19:24 UTC, Seefaaa approved these changes

2024-05-05 20:52 UTC, merged