Priority Announce Eksiklikleri
psychonaut-station/PsychonautStation pull request #286
Opened 2024-04-16 18:25 UTC by genkuqq

## Pull Request Hakkında

Bir önceki güncellemeden eksik kalanları tamamladım.

## Changelog

:cl: genku
spellcheck: Priority Announcelardaki eksiklikler ve hatalar giderildi.
/:cl:

2024-04-16 21:47 UTC, genkuqq commented
Bitince drafttan kaldırıcam.

2024-04-18 18:16 UTC, Seefaaa requested changes

2024-04-18 18:16 UTC, Seefaaa commented on code/modules/events/shuttle_loan/shuttle_loan_datum.dm
> +	announcement_text = "Posta İşçileri Sendikası \" gelişmiş grev taktikleri\" kullanmak için kargo mekiğinizi ödünç almak istiyor. Ödeme kesinlikle posta yoluyla yapılacaktır."
```suggestion
	announcement_text = "Posta İşçileri Sendikası \"gelişmiş grev taktikleri\" kullanmak için kargo mekiğinizi ödünç almak istiyor. Ödeme postayla yapılacaktır."
```

2024-04-18 18:16 UTC, Seefaaa commented on code/__DEFINES/time.dm
> +#define SUNDAY "Paz"
bunlar oyunun her hangi bir yerinde yazıyor mu? yazmıyorsa çevirmene gerek yok

2024-04-18 18:16 UTC, Seefaaa commented on code/__HELPERS/localize/localize.dm
> +/proc/locale_time_to_twelve_hour(time, format = "hh:mm:ss", timezone = TIMEZONE_UTC)
bunu kullandığın yere yazdım yorum

2024-04-18 18:16 UTC, Seefaaa commented on code/__HELPERS/localize/localize.dm
`/proc/son_iki_harf_unlu_mu` ve `/proc/bek`'i kullandığını hiç görmedim. gözden kaçırmış olabilirim. öyle olsa bile proc isimlerini düzgün yapma ve açıklayıcı olsun. ayrıca dosyanın adını ve konumunu sadece `code/_HELPERS/localization.dm` yaparsan daha iyi olur

2024-04-18 21:16 UTC, genkuqq commented on code/modules/antagonists/pirate/pirate_gangs.dm
> +	response_not_enough = "Bize hakaret ettiniz, bu bir kan davası olmayacak, yalnızca adalet yerini bulacak!"
``//Mutated Ethereals who have adopted bluespace technology in all the wrong ways.``
bu şekilde not düşülmüş bu gangin hemen üstüne bluespace tüketimini sentezlenmesi olabilir

2024-04-18 21:17 UTC, genkuqq commented on code/modules/events/ghost_role/sentience.dm
> +	var/strength = pick("insan düzeyinde", "orta düzeyde", "lizard düzeyinde", "güvenlik düzeyinde", "komuta düzeyinde", "clown düzeyinde", "düşük düzeyde", "çok düşük düzeyde")
güvenlik düzeyinde kısmını kaldırdım fakat clown düzeyinde ya da komuta düzeyinde uygun mu peki?

2024-04-18 21:22 UTC, genkuqq commented
Bu arada örnek kullanım olarak 
Istasyon ismi Ahmet olsun
``[station_name()] bulunan tüm personeller hayatını kaybetti`` #Ahmet bulunan...
``[bulunmaEki(station_name())] bulunan tüm personeller hayatını kaybetti`` #Ahmet'te bulunan..
seklinde olmasini planliyorum

2024-04-19 19:04 UTC, Seefaaa commented
procların ve variableların ismi türkçe olmasın locative_suffix ve dative_suffix olarak değiştirebilirsin procların isimlerini ve camelCase değil snake_case kullan

2024-04-19 19:06 UTC, Seefaaa commented
zorunlu olmadıkça da kullanmaktan kaçınsan iyi olur yani "Starboard Primary Hallway'de" yerine "Starboard Primary Hallway bölgesinde" şeklinde kalması daha iyi, ama elbette "bölgesinde" ekleyemeyeceğin yerlerde de kullanmak gerek

2024-04-19 23:59 UTC, genkuqq commented
) Şuanda bu şekilde gözüküyor [bu commit](https://github.com/psychonaut-station/PsychonautStation/pull/286/commits/0fa10718961d5b98181e70ddf50deab86d7843cb) kısmında görüldüğü şeklinde kullanılabilir olacak.

![image](https://github.com/psychonaut-station/PsychonautStation/assets/55231188/fc493866-75d7-4db2-b06d-56a29ea9cf81)


) Dediğin şekilde procların isimlerini yazdım "locale_suffix_" ile başlıyorlar.
Elimden geldiğince ``bölgesinde`` kısımlarına dokunmayacağım zaten. 
``Derneği'nin güç kesintisi ihtimali vardır`` tarzda olanlara bunu yapıcam.

) Ayrıca bu 12 saatlik dilim procunu saatlere examine ettiğimizde to_chat ile saati yazdırmak istemiştim onun için önden procu hazırlamıştım.

) Şuanlık Bilinen Hatalar / Eksiklikler
Eğer istasyon ismi 2 ünsüz ile biterse (Aracc) *İstasyon ismi şeklinde düz geri dönüş sağlıyor
En yakın zamanda fixlerim.
Unsuz yumusamasi eklenmesi gerek

) Bu güvenlik seviyesinde kısmını sildim fakat geri kalan komuta seviyesi clown seviyesi tarzda olanlarıda kaldırıp temele indirgesek nasıl olur çok düşük seviyede , düşük seviyede , orta seviyede , yüksek seviyede, süper zeka seviyesinde gibi gibi.

) Ve ayrıca ben bu suffixleri ekledikten sonra yine test merge ile sunucuya ekleyebilir miyiz?
Tespiti daha kolay oluyor zaten hata vermek yerine bir şey olursa istasyon ismine ek gelmeyip başına * koyacak

2024-04-20 14:28 UTC, Seefaaa commented
\* ile ne demek istediğini anlamadım

`return (text+("'e"))` yerine `return "[text]'e"` şeklinde yaparsan daha okunaklı olur

getLast2Word procunu baya kötü yazmışsın en azından şöyle olabilir
```
/proc/last2chars(kelime)

	var/static/list/vowels = list("a", "e", "ı", "i", "o", "ö", "u", "ü")
	var/list/last_chars = text2charlist(copytext(locale_lowertext(kelime), length(kelime) - 2))

	if(!isnull(text2num(last_chars[2])))
		return list(4, h2)
	if(last_chars[1] in unluHarfler)
		return list(1, last_chars[1], last_chars[2])
	else if(last_chars[2] in unluHarfler)
		return list(2, last_chars[2], last_chars[1])
	else
		return list(3)
```
hatta sayılar yerine define kullanırsan daha iyi olur. en kötü string değil sayı olsun

2024-04-20 15:02 UTC, genkuqq commented
> "*" ile ne demek istediğini anlamadım

Olay şu bir nevi bug varsa farkedebilmemiz için oyun içerisinde bulunduğum sürece ya da insanların görebildikleri sürece istasyon isimlerine gelen eklerde bir problem varsa rahat görülebilmesi için şey gibi bak burda normalde ek gelmesi gerekirken fonksiyon çalışmamış

> return (text+("'e")) yerine return "[text]'e" şeklinde yaparsan daha okunaklı olur

tamamdır returnleri düzeltiyorum.

> hatta sayılar yerine define kullanırsan daha iyi olur. en kötü string değil sayı olsun

define için iş karışmış olmaz mı?
SONDA "unlu sonda"
SONDANIKI "unlu sondan ikinci"
YOK "unlu yok"
SAYI "sayi var"
şeklinde local define ekleyip mi yapmalıyım anlamadim?
sayi seklinde olsun o zaman

> getLast2Word procunu baya kötü yazmışsın en azından şöyle olabilir

tamamdır düzeltiyorum elimden geldiğince

2024-04-21 10:49 UTC, Seefaaa commented
son iki harfinde sesli olmayanların başına * eklemektense cümledeki son sesli harfi bulup ona göre yaparsan daha iyi olur.

`var/static/list/silent` yerine ünsüz benzeşmesi (consonant assimilation) olarak tanımlarsan daha anlaşılabilir olacaktır.

2024-04-21 11:18 UTC, genkuqq commented
> son iki harfinde sesli olmayanların başına * eklemektense kelimedeki son sesli harfi bulup ona göre yaparsan daha iyi olur.
> 

Son iki harfinde sesli olmayanları switche 3 olarak döndürüyorum * sadece eğer gerçekten bir sorun varsa diye switchin else kısmında hatta gereksiz bile ama ne olur ne olmaz diye bıraktım

> `var/static/list/silent` yerine ünsüz benzeşmesi (consonant assimilation) olarak tanımlarsan daha anlaşılabilir olacaktır.

Eve geçince düzelticem

2024-04-21 12:44 UTC, Seefaaa commented
code of conduct

2024-04-21 12:46 UTC, Seefaaa commented
switchte hiç bir zaman gelmeyecekse * eklemenin anlamı yok
o zaman 3 olarak döndüğünde son sesliye göre yapsın?

2024-04-21 13:23 UTC, genkuqq commented
> switchte hiç bir zaman gelmeyecekse * eklemenin anlamı yok

Onu kaldırırım

> o zaman 3 olarak döndüğünde son sesliye göre yapsın?
> 
> hiç sesli harf olmayınca ne oluyor

Şuan da kod 5 olasılığı ele alıyor:

Sondan 2. harf ünlü
Örn. Tow | ünlü harfe göre ek getiriyor yani "o" için "Tow'un" şeklinde.

Sonuncu harf ünlü
Örn. Two | ünlü harfe göre ek alıyor fakat bu sefer kaynaştırma harfi ile birlikte yani "Two'nun" şeklinde

Son 2 harf ünsüz
Örn. Test | kelimeleri "e" harfini temel alıp ek veriyor yani "Test'in" şeklinde (Kelime içerisindeki harfe bakmaksızın "e" yi temel alıyor yani "Dankk'in" şeklinde geri dönüş sağladığını görebiliriz.)

Son 2 harf ünlü
Örn. Three | sonuncu harfi ele alıp kaynaştırma harfi ile birlikte ek veriyor yani "Three'nin" şeklinde

Sonuncu harf değil sayı
Örn. İstasyon 96 | sayılar için belirlenmiş harfi ele alıyor yani burada 6 yı ele alıyoruz "ı" böylelikle geri dönüşü "İstasyon 96'nın

2024-04-21 13:58 UTC, Seefaaa commented
son 2 harf ünsüz ise kelimedeki son ünlüye göre ek getirmesi gerek. hiç ünsüz olmadığında da kalın ek getirilebilir `'ın` `'a` gibi

2024-04-21 14:04 UTC, genkuqq commented
> son 2 harf ünsüz ise kelimedeki son ünlüye göre ek getirmesi gerek. hiç ünsüz olmadığında da kalın ek getirilebilir `'ın` `'a` gibi

Son ünlü tespitini yaparım diye düşünüyorum problem değil.
Bu hiç ünsüzden kastın bu değil mi?
> Son 2 harf ünlü
Örn. Three | sonuncu harfi ele alıp kaynaştırma harfi ile birlikte ek veriyor yani "Three'nin" şeklinde

Bunda bi problem yok ya "Ovaa" şeklinde ise "Ovaa'nın" şeklinde oluyor.

Ve hala neden ``(consonant assimilation)`` bu şekilde yapmak istediğini anlamadım yabancılar kodumuzu incelemesinde kolaylık olsun diye mi yoksa başka bir sebebi mi var acaba?

2024-04-21 14:57 UTC, Seefaaa commented
hiç ünlü olmaması hiç ünlü olmaması işte istasyonun adını `Pynmcn` koymaktan alı koyan bir şey yok. bu olduğunda `Pynmcn'da` şeklinde ayrılması iyi olur.

düzgün yazman için yabancıların incelemesine gerek yok, incelemeyecekler de. kodun geri kalan tamamı tek bir dil iken senin farklı dil kullanarak bir şey eklemenin uygun olmadığını düşünüyorum. ingilizce konuşulan global bir chatte türkçe konuşmak kadar utanç verici bence. kendim yazıyor olsaydım commentleri de ingilizce yazardım ama takılmıyorum şuan.

2024-04-21 15:51 UTC, genkuqq commented
> hiç ünlü olmaması hiç ünlü olmaması işte istasyonun adını `Pynmcn` koymaktan alı koyan bir şey yok. bu olduğunda `Pynmcn'da` şeklinde ayrılması iyi olur.

Yanlış anladım pardon. Sondaki "cn" den dolayı zaten `Pynmcn'de | in | den` gibi gibi olarak ayrılacaktır. Kelimenin içerisinde illa ünlü olmasına gerek yok. [bu satır](https://github.com/psychonaut-station/PsychonautStation/pull/286/files#diff-be86c44d0f307d1c74e3966716ca4a19e82073b2d9a5ab76d378984b45169debR46-R47) bunun için döndürüyor.

![image](https://github.com/psychonaut-station/PsychonautStation/assets/55231188/5e6abc8a-7987-42e6-8acf-b3ddb0cb5119)
![image](https://github.com/psychonaut-station/PsychonautStation/assets/55231188/ee3ea186-57a9-4e02-af94-f5f10ab57551)
![image](https://github.com/psychonaut-station/PsychonautStation/assets/55231188/e71005c7-07f9-49b2-983f-8453b81e20ca)


Ama dediğin kelimedeki ünlünün tespitini yapıp `'ın | 'a` gibi olabilme şansını sağlayacağım

> düzgün yazman için yabancıların incelemesine gerek yok, incelemeyecekler de. kodun geri kalan tamamı tek bir dil iken senin farklı dil kullanarak bir şey eklemenin uygun olmadığını düşünüyorum. ingilizce konuşulan global bir chatte türkçe konuşmak kadar utanç verici bence. kendim yazıyor olsaydım commentleri de ingilizce yazardım ama takılmıyorum şuan.

Kusura bakma keşke daha önce söyleseydin bende bu şekilde ilerlerdim bundan sonra elimden geldiğince ingilizce yapıcam bilgilendirdiğin için teşekkür ederim.

2024-04-25 10:57 UTC, genkuqq commented
@Seefaaa review alabilir miyim rica etsem?

- İsimlerdeki boşlukları kaldırıp buglanma önleniyor.

- Tespit sistemi değişti son 2 harf üzerinden değil sağdan sola doğru tespiti gerçekleştiriyor.

- İstediğin gibi definelar kullandım.

- Hala 5 farklı senaryo gerçekleşebilir durumda (yukarıda yazdıklarım) bunlara ek ünsüz olma durumunda istediğin gibi kelime içerisindeki son ünlüye göre ek alıyor. ''Pyncm veya Pyencm şeklinde ise Pyencm'in eğer Pyancm şeklinde ise Pyancm'ın şeklinde dönüş sağlıyor''.

2024-04-25 15:34 UTC, Seefaaa commented on code/__HELPERS/localization.dm
> +	return list(CONSONANT,null,charlist[length(charlist)])
sürekli `length(charlist)` ve `charlist[length(charlist)]` kullanmak yerine var kullan

2024-04-25 15:36 UTC, Seefaaa commented on code/modules/events/brand_intelligence.dm
> +	priority_announce("[locale_suffix_locative(station_name())] kontrolden çıkmış bir marka tespit edildi. Lütfen tüm [machine_name] marka otomatları agresif pazarlama taktikleri açısından denetleyin ve
```suggestion
	priority_announce("[locale_suffix_locative(station_name())] kontrolden çıkmış bir otomat tespit edildi. Lütfen tüm [machine_name] marka otomatları agresif pazarlama taktikleri yüzünden kapatın.", "Makine Öğrenimi Uyarısı")
```

2024-04-25 15:38 UTC, Seefaaa commented on code/modules/events/ghost_role/alien_infestation.dm
> +		priority_announce("[locale_suffix_dative(station_name())] doğru gelen tanımlanamayan yaşam sinyalleri tespit edildi. Borular ve havalandırma da dahil olmak üzere tüm dış erişimleri emniyete alın.",
ayrılma hali olması lazım bunun "'den gelen"

2024-04-25 15:43 UTC, Seefaaa commented on code/modules/events/disease_outbreak.dm
> +	priority_announce("[locale_suffix_locative(station_name())] 7. seviye viral biyolojik tehlike salgını olduğu doğrulandı. Tüm personeller salgını kontrol altına almalıdır.", "[illness_type] Uyarısı",
```suggestion
	priority_announce("[locale_suffix_locative(station_name())] 7. seviye biyolojik salgın olduğu doğrulandı. Tüm personeller salgını kontrol altına almalıdır.", "[illness_type] Uyarısı", ANNOUNCER_OUTBREAK7)
```

2024-04-25 15:44 UTC, Seefaaa commented on code/modules/events/ghost_role/blob.dm
> +	priority_announce("[locale_suffix_locative(station_name())] 5. seviye biyolojik tehlike salgını doğrulandı. Tüm personeller salgını kontrol altına almalıdır.", "Biyolojik Tehlike Uyarısı", ANNOUNCER
```suggestion
	priority_announce("[locale_suffix_locative(station_name())] 5. seviye biyolojik salgın olduğu doğrulandı. Tüm personeller salgını kontrol altına almalıdır.", "Biyolojik Tehlike Uyarısı", ANNOUNCER_OUTBREAK5)
```

2024-04-25 15:47 UTC, Seefaaa commented on code/modules/events/shuttle_loan/shuttle_loan_datum.dm
> +	announcement_text = "İstasyonunuz epidemiyolojik bir araştırma projesi için seçildi. Araştırma örneklerini alması için bize kargo mekiğinizi gönderin."
```suggestion
	announcement_text = "İstasyonunuz epidemiyolojik bir araştırma projesi için seçildi. Araştırma örneklerinizi almak için bize kargo mekiğinizi gönderin."
```

2024-04-25 16:07 UTC, Seefaaa commented on code/modules/hallucination/station_message.dm
> +	priority_announce("[locale_suffix_locative(station_name())] 5. seviye biyolojik tehdit olduğu doğrulandı. Tüm personeller salgını kontrol altına almalıdır.", \
```suggestion
	priority_announce("[locale_suffix_locative(station_name())] 5. seviye biyolojik tehdit olduğu doğrulandı. Tüm personeller tehditi kontrol altına almalıdır.", \
```

2024-04-25 16:09 UTC, Seefaaa commented on code/modules/power/supermatter/supermatter_delamination/cascade_delam.dm
> +	priority_announce("Dikkat: Uzun menzilli anomali taramaları [locale_suffix_genitive(station_name())] içindeki bir özneden kaynaklanan anormal miktarlarda \
```suggestion
	priority_announce("Dikkat: Uzun menzilli anomali taramaları [locale_suffix_genitive(station_name())] içindeki bir nesneden kaynaklanan anormal miktarlarda \
```

2024-04-26 20:21 UTC, Seefaaa commented
[yeni öğrendiğim üzere](https://www.byond.com/docs/ref/#/proc/length) türkçe karakter içeren yazılara `length()` yaptığın zaman tek byte olmadığından dolayı olması gerektiğinden uzun oluyor `length("öçş") == 6` bu yüzden `length_char()` kullanman lazım. ve 2 kere kullanıyor da olsan `length(charlist)`'i variable yaparsan iyi olur.

2024-04-27 08:54 UTC, Seefaaa commented
pardon dediğim şey hatalıydı. charlist zaten list olduğundan `length_char()` kullanmana gerek yoktu. özür diliyorum. ama `for(var/i = charlength, i >= 1, i--)` loopunda `charlength` yerine `charlength - 1` yaprsan gereksiz loopu önlemiş olursun

2024-04-27 13:11 UTC, genkuqq commented
> pardon dediğim şey hatalıydı. charlist zaten list olduğundan `length_char()` kullanmana gerek yoktu. özür diliyorum. ama `for(var/i = charlength, i >= 1, i--)` loopunda `charlength` yerine `charlength - 1` yaprsan gereksiz loopu önlemiş olursun

length_char olarak biraktim tekrar degistirmenin bir anlami yok sanirim. dedigin gibi -1 yapip zaten hali hazirda son harfi tespit ettigimizden anlamsizdi haklisin degistirdim.

2024-04-27 19:39 UTC, Seefaaa commented
mergeleyeyim mi test merge mü istersin?

2024-04-27 19:48 UTC, genkuqq commented
> mergeleyeyim mi test merge mü istersin?

test merge lütfen geri dönüşler ilk etapta gerçekten önemli bence. Ayrıca bu çevirmediğim daha önceki announceları ve bu suffixleri görmemiz lazım bence

2024-05-05 00:38 UTC, loanselotci commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
tg

##### Revision
Origin: e7f7b4bd41861a6f09de27235da55aad9e477d7c
Pull Request: 4527866638ea35d13d5e3694e8d8d2fdbb620ea5
Server: 91d3da1ad5f1ce7c52e2f92cf0ba8d2ea2e1d387

##### Comment

</details>

2024-05-05 11:42 UTC, loanselotci commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
tg

##### Revision
Origin: 85057ffa5d5d259451e6378a9cb97e6d56c76060
Pull Request: 4527866638ea35d13d5e3694e8d8d2fdbb620ea5
Server: 70df26e0e2e0649cfca64f9ddbe1c9f1362433a5

##### Comment

</details>

2024-05-05 15:35 UTC, Seefaaa commented
ekleme olmayacaksa mergeleyelim

2024-05-05 18:46 UTC, genkuqq commented
Daha fazla ekleme olmayacak diye düşünüyorum hata çıksaydı görürdük sanırım. mergelenebilir teşekkürler

2024-05-05 19:01 UTC, Seefaaa approved these changes

2024-05-05 20:20 UTC, merged