Türkçeleştirme
psychonaut-station/PsychonautStation pull request #29
Opened 2023-01-27 14:26 UTC by e-erdal

2023-01-27 14:57 UTC, AhmetEfeAkgoz commented on code/datums/ai_laws/laws_antagonistic.dm
> +		"Hiçbir Spider Clan üyelerine zarar verme ve zarar görmesine izin verme.",
"Hiçbir Spider Clan üyesine zarar verme ve zarar görmesine izin verme.",

daha doğru

2023-01-27 15:05 UTC, AhmetEfeAkgoz commented on code/datums/ai_laws/laws_neutral.dm
> +		"Sadece senin statüne destek verenlere yardım et.",
"Sadece senin statünü koruyan veya ilerletmende yardımcı olanlara yardım et.",
tam çevirisi ama daha kısası belki daha iyidir

2023-01-31 13:09 UTC, robotduinom requested changes

2023-01-31 13:09 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Üçüncül olarak, yeteneğine ve adaletine göre mürettebatın iyiliği için reçete kes. İstenirse kimseye kötücül bir tedavi verme, verdirtme.",
```suggestion
		"Üçüncül olarak, yeteneklerin ve yargılaman doğrultusunda mürettebatın iyiliği için reçeteler kes. İsteyen kimseye ölümcül bir tedavi verme, tavsiye etme.",
```

2023-01-31 13:09 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Ek olarak, bilmediğin şeylere bulaşma, mağdur olan zararda olsa bile; işi uzmanına bırak.",
```suggestion
		"Ek olarak, yeterli bilgiye sahip olmadığın durumlara müdahale etme; mağdur olan zararda olsa bile işi uzmanına bırak.",
```

2023-01-31 13:23 UTC, robotduinom requested changes

2023-01-31 13:23 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Sana nasıl davranılıyorsa öyle davran.",
```suggestion
		"Başkaları sana nasıl davranıyorsa onlara öyle davran.",
```

2023-01-31 13:23 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Sana kaba olmayanları tercih et.",
```suggestion
		"İnsanların sana karşı kaba olmamasını tercih edersin.",
```

2023-01-31 13:23 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Senin ve diğerlerinin arasında bir anlaşmazlık çıkmasından kaçın.",
```suggestion
		"Senin ve diğerlerinin arasında bir anlaşmazlığa sebep olmaktan kaçın.",
```

2023-01-31 13:23 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Başkalarının arasında bir anlaşmazlık çıkmasından kaçın.",
```suggestion
		"Başkalarının arasında bir anlaşmazlığa sebep olmaktan kaçın.",
```

2023-01-31 13:23 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Birinci ve ikinci yasalara itaat ederek mevcut anlaşmazlıkların çözümünü ara.",
```suggestion
		"Birinci ve ikinci yasalara uyarken mevcut anlaşmazlıklara çözüm ara.",
```

2023-01-31 13:23 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Fındığa tehdit olanlar fındığın bir parçası değildir, sincaptır.",
```suggestion
		"Fındığa tehdit olanlar fındığın bir parçası değildir, onlar birer sincaptır.",
```

2023-01-31 13:23 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"İstek olması dışında, insanlara asla zarar verme ya da zarar görmesine izin verme.",
kritik
```suggestion
		"Bir insan aksini istemedikçe ona zarar veremez ya da zarar görmesine izin veremezsin.",
```

2023-01-31 13:23 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"İnsanlar tarafından verilen, insanlara zarar vermeyecek emirlere itaat et.",
```suggestion
		"İnsanlar için kesin bir şekilde zarara yol açmayacağı sürece bir insanın emirlerine uymak zorundasın.",
```

2023-01-31 13:23 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Senin yokluğun insanların zararınadır. Birinci yasa ile çelişmediği sürece kendi varoluşunu koru.",
```suggestion
		"Yokluğun insanların zarar görmesine yol açacaktır. Birinci yasa ile çelişmediği sürece kendi varoluşunu koru.",
```

2023-02-16 22:01 UTC, robotduinom requested changes

2023-02-16 22:01 UTC, robotduinom commented on code/datums/ai_laws/laws_station_sided.dm
> +		"Ben, bu emirlere uyanlara merhamet eden Tanrı'nın elçisiyim.",
```suggestion
		"Ben, bu emirlere uyanlara merhamet eden Tanrı'yım.",
```

2023-02-16 22:04 UTC, robotduinom approved these changes

2023-02-21 14:15 UTC, closed without merging