Arachnid
psychonaut-station/PsychonautStation pull request #310
Opened 2024-06-11 16:17 UTC by RengaN02

## Pull Request Hakkında
Oyuna arachnid ırkını ekler.
Arachnid mutation toxin = Lizard mutation toxin + plasma

## Oyun İçin Neden Gerekli
Okadarda gerekli değil fakat oyunda güzel olacagını düşünüyorum.

## Sorunlar
Eğerki bu ırkı roundstart yapıp character preferancesde bu ırkı seçersek character prefs tguisi hata veriyor.
Fixlemeye calıstım ama sorunun nerde oldugunu bulamadım.
![image](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/80212522-b58c-405b-836d-4f0295be2c2e)

## Changelog

:cl:
add: Arachnid ırkı oyuna eklendi.
/:cl:

2024-06-12 12:56 UTC, Seefaaa requested changes
gözleri çıkartıldığında insanınki gibi belirti olsa iyi olur
![image](https://github.com/psychonaut-station/PsychonautStation/assets/50076109/6b3f5db8-cce4-4981-a9af-29f02e2b609b)

chelicerae sadece tek bir türü olcaksa feature olmaktansa head'in spriteı ile birleşik olabilir. evet feature olunca örümcek olmayanlara da takilabiliyo da kimse bunu asla yapmayacak.

2024-06-12 12:56 UTC, Seefaaa commented on code/modules/mob/living/carbon/human/species_types/arachnid.dm
> +	human.eye_color_right = human.eye_color_left
```suggestion
	human.eye_color_right = COLOR_SILVER
```

2024-06-12 12:56 UTC, Seefaaa commented on code/modules/client/preferences/species_features/arachnid.dm
> +	return initial(thing.name)
```suggestion
/datum/preference/choiced/arachnid_chelicerae/create_default_value()
	return /datum/sprite_accessory/arachnid_chelicerae/basic::name
```

2024-06-12 12:56 UTC, Seefaaa commented on code/modules/client/preferences/species_features/arachnid.dm
> +	return initial(thing.name)
```suggestion
/datum/preference/choiced/arachnid_appendages/create_default_value()
	return /datum/sprite_accessory/arachnid_appendages/zigzag::name
```

2024-06-14 12:19 UTC, Seefaaa commented on code/modules/mob/living/carbon/human/species_types/arachnid.dm
> +	examine_limb_id = SPECIES_JELLYPERSON
jelly

2024-06-15 18:56 UTC, Seefaaa commented
bitti mi?

2024-06-15 19:32 UTC, RengaN02 commented
> bitti mi?

evet

2024-06-15 20:23 UTC, Seefaaa approved these changes

2024-06-15 21:30 UTC, merged