Yeni Animal Vada/Gold Slime
psychonaut-station/PsychonautStation pull request #326
Opened 2024-06-23 14:30 UTC by MrEmre12

## Pull Request Hakkında

Diğer pek çok hayvanda olduğu gibi hem gold slime içinden çıkıyor hemde oyuncular kontrol edebiliyor.

## Oyun İçin Neden Gerekli

Vada karakteri çok seviliyor ilgiyi karşılar diye umut ediyorum.

https://github.com/psychonaut-station/PsychonautStation/assets/157297522/cd729f70-c34c-468a-b913-5e8ef443872d

![Ekran görüntüsü 2024-06-23 172636](https://github.com/psychonaut-station/PsychonautStation/assets/157297522/06c9a37f-9105-4094-99cf-c6927be9633e)
![Ekran görüntüsü 2024-06-23 154655](https://github.com/psychonaut-station/PsychonautStation/assets/157297522/b58aaa5e-43a1-4741-a33a-93713102e4fd)

## Changelog

Vada eklendi.

:cl:
add: Yeni Animal Vada/Gold Slime.
/:cl:

2024-06-23 14:42 UTC, exdal requested changes

2024-06-23 14:42 UTC, exdal commented on code/datums/ai/basic_mobs/basic_subtrees/speech_subtree.dm
> +	sound = list('sound/_psychonaut/amınake.ogg', 'sound/_psychonaut/wada.ogg')
turkce karakter iceren dosya kullanma

2024-06-23 14:42 UTC, exdal commented on code/datums/ai/basic_mobs/basic_subtrees/speech_subtree.dm
> +	emote_hear = list("Gah Gah!", "NOOT NOOT!", "NOOT!", "Noot", "noot", "Prah!", "Grah!")
emotelar kucuk harfle baslar, noktalama isaretlerini de unutma

2024-06-23 14:42 UTC, exdal commented on code/modules/mob/living/basic/space_fauna/vada.dm
> +	death_message = "VADAA :(...)"
daha iyi bir death message lazim, :( gibi OOC seyler icermesin

2024-06-23 14:42 UTC, exdal commented on code/modules/mob/living/basic/space_fauna/vada.dm
> +	butcher_results = list(/obj/item/stack/ore/plasma = 1,)
```suggestion
	butcher_results = list(/obj/item/stack/ore/plasma = 1)
```

2024-06-23 15:11 UTC, exdal approved these changes
secilebilir animal olmasi konusunda emin degilim sefa'ya kalmis

2024-06-23 18:35 UTC, Seefaaa requested changes
sesleri sound/_psychonaut diye koymana gerek yok
küfür ve sürekli duyulcağından aminake sesi istemiyorum

2024-06-23 18:35 UTC, Seefaaa commented on code/modules/mob/living/basic/space_fauna/vada.dm
> +	)
saldırınca geri saldırmak yerine sadece kaçması daha uygun olur heralde

2024-06-23 18:35 UTC, Seefaaa commented on code/modules/client/preferences/animal_type.dm
> +	"Vada" = /mob/living/basic/vada,
```suggestion
```
yok

2024-06-23 18:35 UTC, Seefaaa commented on code/datums/ai/basic_mobs/basic_subtrees/speech_subtree.dm
> +
```suggestion
/datum/ai_planning_subtree/random_speech/vada
	speech_chance = 10
	speak = list("vadee.", "amınake!!",)
	sound = list('sound/_psychonaut/aminake.ogg', 'sound/_psychonaut/wada.ogg')
	emote_hear = list("vada!", "vadeee.", "amınake!!")
	emote_see = list("vadee.", "vada!!")

```
ı yerine i yazmıssın kasıtlı mı bilmiyorum

2024-06-23 19:30 UTC, Seefaaa requested changes
wada.ogg'yi sound/creatures içerisine koy

2024-06-24 01:18 UTC, Seefaaa approved these changes

2024-06-24 01:35 UTC, merged