Ayran Düzeltmeleri
psychonaut-station/PsychonautStation pull request #352
Opened 2024-08-05 19:21 UTC by meatflowse

## Pull Request Hakkında
Boozomatta satılan bardak ayran 100u luk şişe ayran olarak değişti.
Artık bardağa ayran eklendiğinde özel sprite oluşuyor.
![image](https://github.com/user-attachments/assets/3fe69e49-4dd1-4696-b4c6-1aa80fb5a7ee)
![image](https://github.com/user-attachments/assets/baa148cf-ef17-4588-9aa5-178d8507d57d)

## Oyun İçin Neden Gerekli
Daha hoş gözüküyor ve daha işlevli.

## Changelog

:cl:
add: Yeni bardak ve şişe ayran spriteı eklendi.
add: Boozeomatta bardak ayran yerine şişe ayran satılıyor.
add: Artık ayran bardağa doldurulduğunda sprite değişiyor.
/:cl:

2024-08-05 22:38 UTC, Seefaaa requested changes

2024-08-05 22:38 UTC, Seefaaa commented on code/modules/reagents/chemistry/reagents/drinks/drink_reagents.dm
> -	default_container = /obj/item/reagent_containers/cup/glass/ayran
bunu kaldırmak yerine yeni eklediğin bottle yapsan iyi olur yoksa böyle gözüküyo
![image](https://github.com/user-attachments/assets/547a34df-76db-404b-8e41-5d5e6de4fda7)

2024-08-05 22:38 UTC, Seefaaa commented on code/modules/reagents/reagent_containers/cups/bottle.dm
> +
chem bottle overlayi gözüküyor üzerinde ayrıca iconun boyutu çok büyük süt kutusu ile yakın boyutta yaparsan iyi olur
![image](https://github.com/user-attachments/assets/1fc3e103-90f2-43e6-8ded-08c38efd5ae4)

2024-08-05 22:38 UTC, Seefaaa commented on icons/psychonaut/obj/drinks/drinks.dmi
oyundaki bardaklara benzemesi lazım
![image](https://github.com/user-attachments/assets/332ec0ad-a975-4ee0-afe7-074ddb479020)

2024-08-06 08:45 UTC, meatflowse commented on icons/psychonaut/obj/drinks/drinks.dmi
![image](https://github.com/user-attachments/assets/7056d13c-9e23-4756-bd4e-aacafad65d55)

2024-08-06 20:23 UTC, Seefaaa approved these changes

2024-08-06 20:40 UTC, merged