Animal Revival
psychonaut-station/PsychonautStation pull request #53
Opened 2023-05-12 20:26 UTC by AhmetEfeAkgoz

Rengar ilen animal revival ameliyatı (denenmedi)

2023-05-12 20:26 UTC, AhmetEfeAkgoz commented
katanayı unutmuşum

2023-05-12 20:27 UTC, AhmetEfeAkgoz commented
> katanayı unutmuşum

katana yokmuş sorun yok

2023-05-12 20:38 UTC, RengaN02 commented
çok iyi bence

2023-05-15 13:29 UTC, AhmetEfeAkgoz commented
bunu ekleme daha yapılcak

2023-06-12 11:21 UTC, RengaN02 commented on code/modules/surgery/revival.dm
kod bozuk düzeltilmiş halini discord maintainer kanalına attım

2023-06-12 11:23 UTC, RengaN02 requested changes
revival dosyası bozuk onun dışında iyi

2023-06-12 13:18 UTC, RengaN02 approved these changes
hata yok gibi

2023-06-19 13:33 UTC, exdal commented
#55

2023-06-19 13:33 UTC, closed without merging