New anomalys and Animal revival
psychonaut-station/PsychonautStation pull request #55
Opened 2023-06-18 21:34 UTC by RengaN02

- New anomalys
    + Life anomaly
    + Time anomaly
- Surgery
    + Animal revival

Hatalar vardı yapabildiğim kadar düzelttim.

Yapımında yarcımcı olanlar:

- Sad Seal

2023-06-18 21:40 UTC, RengaN02 commented
Spriteleri değiştirmek isteyebilirsiniz pek iyi değilim sprite konusunda

2023-06-18 22:24 UTC, exdal commented
sci'ye buff yok, time anomaly ve eventlerini kaldir

2023-06-18 22:27 UTC, exdal requested changes
time anomaly sci'yi yeterince allah yapiyor, ayrica ekledigin spritelarin resimlerini koy

2023-06-19 08:51 UTC, RengaN02 commented
> time anomaly sci'yi yeterince allah yapiyor, ayrica ekledigin spritelarin resimlerini koy

dengeleme yapıyorum, spriteler dmi dosyaları içinde hali hazırda duruyor başka nereye eklemeliyim. Aynı zamanda hata veren kısımları anlamadım ama yinede düzeltmeye calısacagım

2023-06-19 09:25 UTC, RengaN02 commented
![anomaly_core_left](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/051088d0-f8b3-4a4a-83a6-e7acfc3b532f)
![dimensional_anomaly](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/677e3a49-f636-48a4-b5cb-6363279799db)
![dimensional-left](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/e539627d-ab54-4a86-a213-0cbe16df8739)
![life_anomaly](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/130684cb-18b9-43fb-baae-3b6376129dbb)
![life_anomaly_left](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/fa238685-ffb3-4ead-aafe-f86f7ff5ee07)
![rawcore_anomaly](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/0e9289f0-ae86-4c2a-a47f-c974dad3ceee)
![rawcore_dimensional](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/81334913-bbd8-42eb-be7a-ef5144f280a9)
![rawcore_life_anomaly](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/768633c3-149f-4ad8-b75b-5a15ed01f499)
![anomaly_core](https://github.com/psychonaut-station/PsychonautStation/assets/60517664/447be122-e3df-4326-9613-bad3e52f261d)


Spriteleride atmam gereken konumu söylemediğiniz için buraya yazdım

2023-06-22 18:38 UTC, closed without merging